FROM docker:dind
RUN apk --no-cache add curl wget git make musl-dev go
# --- setup kubernetes part ---
RUN curl -sLo /usr/local/bin/kubectl 'https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl' && chmod +x /usr/local/bin/kubectl
RUN curl -Lo /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/v0.6.1/kind-$(uname)-amd64 && chmod +x /usr/local/bin/kind
# --- setup goenv ---
#WORKDIR /tmp
#RUN wget 'https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz' && tar -C /usr/local -xzf 'go1.13.5.linux-amd64.tar.gz'
#ENV PATH $PATH:/usr/local/go/bin
# Configure Go
ENV GOROOT /usr/lib/go
ENV GOPATH /go
ENV PATH /go/bin:$PATH
# --- container service part
ENV CGO_ENABLED=0
WORKDIR /kw
COPY . .