name: Go
on: 
  push:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: golang test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: build image
        run: docker build -t kw_test -f Dockerfile.test .
      
      - name: activate container
        run: docker run -it --privileged --name kw_test -d kw_test && sleep 5
      
      - name: create cluster
        run: docker exec -it kw_test sh ./init.sh
      
      - name: run test
        run: docker exec -it kw_test go test ./...
